### ISSUE TITLE
Single player mode broken

### ISSUE THREAD

**Issue by johanmoritz** [johanmoritz/heard-when-vue3#11]
One player doesn't work proparly (maybe shouldn't even be able to be one player). The cards are now cleared every time, whether correct answers, locked or not.

**Comment by johanmoritz** [comment]
This is a wierd one. I haven't spent much time on it as it doesn't really matter. I think for now we keep it as it is and then we add a constraint next week that you need at least 2 players to start the game.
What do think @emmariaolsson  @LeoBergqvist  @axelmjohansson ?

**Comment by emmariaolsson** [comment]
I think it can be good to keep it (although a bit buggy) as we develop since it's not always possible to play two players on the localhost if you don't have more emails and so on. But I definitely think we should add a constraint towards the end and maybe a message to the game-creator that you need to wait for at least one more player.

**Comment by johanmoritz** [comment]
I've actually fixed this.
